openapi: 3.0.2
info:
  title: Apigee Firestore Asset
  version: 1.0.0-oas3
  description: Apigee Firestore Asset Management
  contact:
    email: lalevee@google.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: 'https://emea-demo7-test.apigee.net/v1/firestore'
security:
  - api_key: []
  
paths:

  /asset:
    get:
      tags:
        - asset
      summary: List all assets
      responses:
        '200':
          description: Asset list retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/asset-list'
    post:
      tags:
        - asset
      summary: Insert an asset 
      requestBody:
        description: Asset to be created
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/asset'
      responses:
        '200':
          description: OK
        '400':
          description: Invalid asset supplied
          
  '/asset/{id}':
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: The asset id
    get:
      tags:
        - asset
      summary: Get an asset by id
      responses:
        '200':
          description: Asset retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/assetobj'
        '404':
          description: Asset not found
    put:
      tags:
        - asset
      summary: Update an asset by id
      requestBody:
        description: Asset to be created
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/asset'
      responses:
        '200':
          description: Asset retrieved
        '400':
          description: Invalid asset supplied
        '404':
          description: Asset not found 
    delete:
      tags:
        - asset
      summary: Delete the asset by id
      responses:
        '200':
          description: OK
        '404':
          description: Asset not found
components:
  schemas:
  
    assetobj:
      type: object
      properties:
        asset:
          $ref: '#/components/schemas/asset'
      
      
    asset:
      type: object
      properties:
        description:
          type: string
        id:
          description: asset unique id
          type: string
        keywords:
          description: 'list of keyword, separated by commas'
          type: string
        link:
          description: Asset URL
          type: string
        title:
          description: asset title
          type: string
        type:
          description: Asset type
          type: string
          enum:
            - html
            - gSlides
            - gDocs
            - pdf
        sharable:
          description: sharable with non Googler
          type: boolean
      example:   # Sample asset object
        description: "Get answers, ideas, and support from the Apigee Community"
        id: "community"
        keywords: "community, faq, question, howto"
        link: "https://community.apigee.com/"
        title: "Apigee Community"
        type: "web"
        sharable: false
        
    asset-list:
      type: object
      properties:
        asset:
          type: array
          items:
            $ref: '#/components/schemas/asset'
      example:   # Sample asset object
          asset:
          - description: "Get answers, ideas, and support from the Apigee Community"
            id: "community"
            keywords: "community, faq, question, howto"
            link: "https://community.apigee.com/"
            title: "Apigee Community"
            type: "web"
            sharable: false
          - description: "A comparison matrix of all available Apigee offerings"
            id: "offering"
            keywords: "offering, entitlement, standard, enterprise"
            link: "https://specs.apigee.com/files/Apigee_Offerings.pdf"
            title: "Apigee Offerings"
            type: "pdf"
            sharable: true
          
  securitySchemes:
    api_key:
      type: apiKey
      name: x-apikey
      in: header
      