openapi: 3.0.2
info:
  title: Apigee AMI User
  version: 1.0.0-oas3
  description: Apigee User Management
  contact:
    email: lalevee@google.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: 'https://emea-demo7-test.apigee.net/v1/ami'
security:
  - api_key: []
  
paths:

  /user:
    get:
      tags:
        - user
      summary: List all users
      responses:
        '200':
          description: User list retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user-list'

    post:
      tags:
        - user
      summary: Insert an user 
      requestBody:
        description: User to be created
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
      responses:
        '200':
          description: OK
        '400':
          description: Invalid user supplied
  '/user/{name}':
    parameters:
      - in: path
        name: name
        schema:
          type: string
        required: true
        description: The user name
    get:
      tags:
        - user
      summary: Get an user by name
      responses:
        '200':
          description: User retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userobj'
        '404':
          description: User not found
    put:
      tags:
        - user
      summary: Update an user by name
      requestBody:
        description: User to be created
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
      responses:
        '200':
          description: User retrieved
        '400':
          description: Invalid user supplied
        '404':
          description: User not found
    delete:
      tags:
        - user
      summary: Delete the user with the specified name
      responses:
        '200':
          description: OK
        '404':
          description: User not found
components:
  schemas:
  
    userobj:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/user'
      
      
    user:
      type: object
      properties:
        email:
          type: string
        first-name:
          type: string
        last-name:
          type: string
        name:
          type: string
          description: user unic full name (id)
        role:
          type: string
 
      example:   # Sample user object
        email: "georges@sample.com"
        first-name: "Georges"
        last-name: "Habitbol"
        name: "ghabitbol"
        role: "admin"
        
    user-list:
      type: object
      properties:
        user:
          type: array
          items:
            $ref: '#/components/schemas/user'
      example:   # Sample user object
          user:
          - email: "georges@sample.com"
            first-name: "Georges"
            last-name: "Habitbol"
            name: "ghabitbol"
            role: "admin"
          - email: "xtof@sample.com"
            first-name: "Xtof"
            last-name: "Raising"
            name: "xraising"
            role: "user"
          
  securitySchemes:
    api_key:
      type: apiKey
      name: x-apikey
      in: header
      